site_name: My Docs
nav:
    - Dashboards: dashboards.md
    - Integrations: integrations.md
    - Projects: projects.md
    - Registration: registration.md
    - TestRuns: testruns.md
    - UserProfile: userprofile.md
    - UserGroups: usergroups.md
    - Widgets: widgets.md
theme: 
  name: 'material'
repo_url: https://github.com/APGorobets/mkdocks1
repo_name: Github
